### ISSUE TITLE
Request for Colab that shows how to run the code in a simple manner

### ISSUE THREAD

**Issue by sfm-user-1** [zhangganlin/GlobalSfMpy#11]
Hi, most SfM libraries like hloc, pycolmap etc include a [Colab notebook](https://colab.research.google.com/drive/1MrVs9b8aQYODtOGkoaGNF9Nji3sbCNMQ) where users can upload images and users can test the code on sample image sets. Can the authors please provide such a colab?

**Comment by zhangganlin** [comment]
Hi, currently I have no plan for colab
