### ISSUE TITLE
Question about uncertainty

### ISSUE THREAD

**Issue by TwiceMao** [zhangganlin/GlobalSfMpy#2]
Out of my understanding of your paper, the _uncertainty_ is the _covariance_ C(Rij ). 

![image](https://github.com/zhangganlin/GlobalSfMpy/assets/43490149/9a4e4ed7-a6c1-4d8f-a5ad-61e65a9845c9)

But, it seems that there is no description of how covariance C(Rij ) is used.
I mean, you just give a concept of C(Rij ), but do not tell us how it is utilized.
So I want more details, thx~~~~
Please forgive me if I understand wrong

**Comment by zhangganlin** [comment]
Hi,

As shown in equ(3), we use this uncertainty to weight the loss in the optimization process.
![Screenshot from 2023-06-30 13-33-46](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/71684827-4d6e-4371-a584-c9003d513178)

Here $D_{ij}$ is LLT decomposition of $C(R_{ij}^{A})^{-1}$

![Screenshot from 2023-06-30 13-34-19](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/3957ec9f-f36a-4881-b385-6253f23693aa)

Hope that answers your questions :)

Ganlin

**Comment by TwiceMao** [comment]
Thx!!!
