### ISSUE TITLE
Lack of reproducibility of paper + code

### ISSUE THREAD

**Issue by sfm-user-1** [zhangganlin/GlobalSfMpy#3]
Hi @zhangganlin, thanks for releasing the code and congrats on the CVPR paper. However, I would like to note that this work is not close to reproducible in its current form. It appears to depend on a 5-year old commit of an unmaintained SfM library (Theia), with dozens of dependencies that are now out of date or incompatible.

I'd respectively ask for a full, working install script for Ubuntu on a clean ec2 instance, or python bindings that could be install via pypi or conda.

The install directions are only given as follows in the README:
```
TheiaSfM (Recommand version 0.7.0)
Ceres (Recommand version 1.14.0)
pybind11 (Recommand version 2.9.2)
OpenCV
(Optional) COLMAP (Recommand version 3.6)
```

Not listed would be only Eigen 3.3.7, but no other version, and gflags, libatlas, libsuitesparse, OIIOopenexr, TIFF, boost, etc. None of which are compatible in their current state. This isn't fair to practitioners who wish to reproduce results.

Thanks in advance for your consideration.

**Comment by sfm-user-1** [comment]
@zhangganlin @danini @vlarsson Would it be possible to provide more detailed installation instructions to assist in reproducibility, and to release the scripts you used to run the experiments over the 13 scenes in the paper? This paper seems like really great work but in its current state the codebase is difficult to work with.

**Comment by zhangganlin** [comment]
Hi, 

Sorry for the late reply, I would try to provide more detailed instruction later

Ganlin

**Comment by sfm-user-1** [comment]
Thanks. @zhangganlin @danini @vlarsson any ETA on when more documentation could be provided to the repo, in order to reproduce the CVPR paper results? (It's been about 2.5 months now)

**Comment by zhangganlin** [comment]
I am really busy at the moment, hopefully the instruction could be updated in a few weeks.
Actually, all the other libraries are just dependencies of Ceres and Theia, so once you installed the mentioned version of Ceres and Theia successfully, it should just work. Anyway, I would try to make it more clear later. 
Please just be patient.

**Comment by sfm-user-1** [comment]
Hi @zhangganlin @danini @vlarsson any update on when full install instructions could be given to reproduce Tables 1 and 5 from your paper, on a fresh ec2 ubuntu instance? (could we provide an install script please)

**Comment by zhangganlin** [comment]
Thanks for the reminder, I’ll update it before the end of this week at the latest

**Comment by zhangganlin** [comment]
I have update a more detailed install instruction in README, but since I currently do not have a clean machine to test from scratch, it is still possible that I miss some dependencies there. Let me know if that happens.
