### ISSUE TITLE
C++ YAML dependency? 

### ISSUE THREAD

**Issue by akshay-krishnan** [zhangganlin/GlobalSfMpy#4]
Thanks for making the code available, and great work with the paper!

In addition to the dependencies you mention, it looks like the library also depends on yaml-cpp? 
I had to download `yaml-cpp` from https://github.com/jbeder/yaml-cpp, build it from source and add the dependency to the list of linked libraries for GlobalSfmPy. 

Was this step specific to me because of my setup / C++ version?  If not, could it be added to the list of dependencies?

**Comment by zhangganlin** [comment]
Thanks for pointing that out, I just installed yaml-cpp by ''apt install'', so did not realize this is also a dependency of this project when I wrote the readme
```bash
sudo apt install libyaml-cpp-dev
```
