### ISSUE TITLE
expected result for Madrid metropolis?

### ISSUE THREAD

**Issue by akshay-krishnan** [zhangganlin/GlobalSfMpy#5]
Hi!

I was able to setup the library and run the Madrid Metropolis example. I just want to confirm whether this looks like the result one would expect: 

![madrid_snap00](https://github.com/zhangganlin/GlobalSfMpy/assets/24805051/471b059d-1a09-42cf-a163-628f81f9df18)

It would be great if you could add some screenshots of your Madrid Metropolis visualization to the readme, so users can know whether they got the expected result.  

I made some changes, both to setup the library and to write the results to a PLY file, which are here: https://github.com/akshay-krishnan/GlobalSfMpy/tree/repro-changes. Let me know if you'd like me to create a PR to merge those changes.

**Comment by akshay-krishnan** [comment]
The pointcloud originally looked much more noisy (has a lot of outliers), and we had to trim it to a specific region to get the above visualization. 

Original visualization: 
![image](https://github.com/zhangganlin/GlobalSfMpy/assets/24805051/d2841e88-4308-4d2c-bf9f-81bbabeed4cc)

**Comment by zhangganlin** [comment]
Hi Akshay, 
I haven't try to visualize these results in meshlab but according to your screenshot, it looks reasonable. For the outlier your mensioned, it might be some other buildings along the street.
I put my original result here (visualized by Theia), and will update it into the readme.
For the PR, I'm happy to merge them into the main branch. Thanks for the modification!
![demo](https://github.com/zhangganlin/GlobalSfMpy/assets/32034109/b76b08ad-a888-472c-899b-f8486b377e36)

**Comment by zhangganlin** [comment]
For the yaml-cpp dependency, I still prefer the way to install directly by command line to make it clear, as I replied here #4

**Comment by akshay-krishnan** [comment]
Thanks for confirming!
re yaml-cpp: makes sense, I opened a PR with the other changes.
