### ISSUE TITLE
SuperPoint + SuperGlue for the 1DSfM datasets?

### ISSUE THREAD

**Issue by travisdriver** [zhangganlin/GlobalSfMpy#7]
Great work on this paper, and thank you for open sourcing the code!

Did you use SuperPoint + SuperGlue for the 1DSfM datasets results (e.g., Gendarmenmarkt)? The paper states SP + SG was used for the ETH3D datasets, but I wasn't sure if it was used for the 1DSfM datasets as well.

**Comment by zhangganlin** [comment]
Hi,
For the 1dsfm experiments, we just used the feature matching results provided by the dataset (should be SIFT).
