### ISSUE TITLE
Hard-coded paths in source code

### ISSUE THREAD

**Issue by sfm-user-1** [zhangganlin/GlobalSfMpy#8]
I find the scripts have hard-coded paths, e.g. to 
```
    imwrite("/home/zhangganlin/Desktop/CVG/GlobalSfMpy/outlier/colmap/"+view2.Name(),img_matches);
```
https://github.com/zhangganlin/GlobalSfMpy/blob/ad788eb4abd7f3996d51680fd1557b14508d4583/src/feature_inliers.cpp#L106C1-L107C1
This is in the `get_inliners()` function. Did you mean inliers? I find the source code is not usable as-is due to these hard-coded paths.

Another example:
```
dataset_path = "/home/zhangganlin/Desktop/CVG/final_version_globalsfmpy/datasets/"+dataset_name
```

https://github.com/zhangganlin/GlobalSfMpy/blob/main/scripts/sfm_with_colmap_feature.py#L20

Could the source code and all scripts be updated to accept an arbitrary path over command line?

**Comment by zhangganlin** [comment]
For the function name, yes it is a typo, I'll fix it later.
I'm sorry for the inconvenience of the hard-coded path, the one in ```feature_inliers.cpp``` is just for visualization for debugging, you can just remove  this part https://github.com/zhangganlin/GlobalSfMpy/blob/ad788eb4abd7f3996d51680fd1557b14508d4583/src/feature_inliers.cpp#L99C4-L111C107
And for the python script, just replace that with your path.
Anyway, I'll try to fix those issues later

**Comment by sfm-user-1** [comment]
Hi @zhangganlin, any ETA on when these hard-coded file paths will be removed from the source? Haven't been able to reproduce the results of the paper yet because of this.

**Comment by zhangganlin** [comment]
Hi, I have already removed the hard-coded path in C++, and for the python script, since it is an example scripts and easy for user to change, I just keep it
