### ISSUE TITLE
Paper uses ground truth data as input to SfM pipeline

### ISSUE THREAD

**Issue by sfm-user-1** [zhangganlin/GlobalSfMpy#9]
@zhangganlin I find that in Section 4 of the [CVPR paper](https://openaccess.thecvf.com/content/CVPR2023/papers/Zhang_Revisiting_Rotation_Averaging_Uncertainties_and_Robust_Losses_CVPR_2023_paper.pdf), the authors say about ETH3D:
```
We use the 13 scenes of the training set, and use all image pairs with at least 500 GT keypoints in common.
```

This seems very unfair, as it means the paper uses ground truth data as input to their SfM pipeline (determining image pairs using GT data). Choosing image pairs (retrieval) is one of the hardest parts of SfM, so this makes the task almost trivial. Could the authors please re-run this ETH3D experiment and update the Arxiv paper, without leaking the ground truth into the evaluation?

**Comment by zhangganlin** [comment]
Hi, 
I agree that constructing the view graph is an essential step of SfM, however, for this paper, what we focus on is only the Rotation Averaging stage, which needs the constructed view graph as input. The task of choosing image pairs is actually out of the scope of this paper. 
Also, all the methods mentioned in the paper are given the same feature matching inputs to make sure the comparison is fair.
